Install-Module -AllowPrerelease -Force -Verbose -Name 7Zip4Powershell
Install-Module -AllowPrerelease -Force -Verbose -Name AudioDeviceCmdlets
Install-Module -AllowPrerelease -Force -Verbose -Name Carbon
Install-Module -AllowPrerelease -Force -Verbose -Name ChocolateyGet
Install-Module -AllowPrerelease -Force -Verbose -Name CmdMode
Install-Module -AllowPrerelease -Force -Verbose -Name Cobalt
Install-Module -AllowPrerelease -Force -Verbose -Name CodeConversion
Install-Module -AllowPrerelease -Force -Verbose -Name Configuration
Install-Module -AllowPrerelease -Force -Verbose -Name Convert
Install-Module -AllowPrerelease -Force -Verbose -Name DSCR_FileAssoc
Install-Module -AllowPrerelease -Force -Verbose -Name EditorServicesCommandSuite
Install-Module -AllowPrerelease -Force -Verbose -Name EzTheme
Install-Module -AllowPrerelease -Force -Verbose -Name Foil
Install-Module -AllowPrerelease -Force -Verbose -Name FontUtilities
Install-Module -AllowPrerelease -Force -Verbose -Name Get-ActiveSession
Install-Module -AllowPrerelease -Force -Verbose -Name Get-ChildItemColor
Install-Module -AllowPrerelease -Force -Verbose -Name Get-MediaInfo
Install-Module -AllowPrerelease -Force -Verbose -Name Graphical
Install-Module -AllowPrerelease -Force -Verbose -Name GuiCompletion
Install-Module -AllowPrerelease -Force -Verbose -Name IconForGUI
Install-Module -AllowPrerelease -Force -Verbose -Name Logging
Install-Module -AllowPrerelease -Force -Verbose -Name Metadata
Install-Module -AllowPrerelease -Force -Verbose -Name Microsoft.PowerShell.Archive
Install-Module -AllowPrerelease -Force -Verbose -Name Microsoft.PowerShell.ConsoleGuiTools
Install-Module -AllowPrerelease -Force -Verbose -Name Microsoft.PowerShell.Crescendo
Install-Module -AllowPrerelease -Force -Verbose -Name Microsoft.PowerShell.WhatsNew
Install-Module -AllowPrerelease -Force -Verbose -Name ModuleBuilder
Install-Module -AllowPrerelease -Force -Verbose -Name MSTerminalSettings
Install-Module -AllowPrerelease -Force -Verbose -Name oh-my-posh
Install-Module -AllowPrerelease -Force -Verbose -Name Pansies
Install-Module -AllowPrerelease -Force -Verbose -Name platyPS
Install-Module -AllowPrerelease -Force -Verbose -Name Posh-SSH
Install-Module -AllowPrerelease -Force -Verbose -Name posh-sshell
Install-Module -AllowPrerelease -Force -Verbose -Name PoshColor
Install-Module -AllowPrerelease -Force -Verbose -Name PoshHosts
Install-Module -AllowPrerelease -Force -Verbose -Name PoShLog
Install-Module -AllowPrerelease -Force -Verbose -Name PowerLine
Install-Module -AllowPrerelease -Force -Verbose -Name PowerRemoteDesktop_Server
Install-Module -AllowPrerelease -Force -Verbose -Name PowerRemoteDesktop_Viewer
Install-Module -AllowPrerelease -Force -Verbose -Name PowerShellCookbook
Install-Module -AllowPrerelease -Force -Verbose -Name PowerShellForGitHub
Install-Module -AllowPrerelease -Force -Verbose -Name PowerShellGet
Install-Module -AllowPrerelease -Force -Verbose -Name ps2exe
Install-Module -AllowPrerelease -Force -Verbose -Name PsComplete
Install-Module -AllowPrerelease -Force -Verbose -Name PSConsoleTheme
Install-Module -AllowPrerelease -Force -Verbose -Name PSDesiredStateConfiguration
Install-Module -AllowPrerelease -Force -Verbose -Name PSEverything
Install-Module -AllowPrerelease -Force -Verbose -Name PSExpandLine
Install-Module -AllowPrerelease -Force -Verbose -Name PSFzf
Install-Module -AllowPrerelease -Force -Verbose -Name PSGalleryExplorer
Install-Module -AllowPrerelease -Force -Verbose -Name PSOneTools
Install-Module -AllowPrerelease -Force -Verbose -Name PSParallel
Install-Module -AllowPrerelease -Force -Verbose -Name PSPGP
Install-Module -AllowPrerelease -Force -Verbose -Name PSReadLine
Install-Module -AllowPrerelease -Force -Verbose -Name PSScriptAnalyzer
Install-Module -AllowPrerelease -Force -Verbose -Name PSScriptMenuGui
Install-Module -AllowPrerelease -Force -Verbose -Name PSScriptTools
Install-Module -AllowPrerelease -Force -Verbose -Name PSStringTemplate
Install-Module -AllowPrerelease -Force -Verbose -Name PSWindowsTermina
Install-Module -AllowPrerelease -Force -Verbose -Name PSWindowsUpdate
Install-Module -AllowPrerelease -Force -Verbose -Name TerminalBlocks
Install-Module -AllowPrerelease -Force -Verbose -Name Theme.PowerShell
Install-Module -AllowPrerelease -Force -Verbose -Name Theme.PSReadLine
Install-Module -AllowPrerelease -Force -Verbose -Name Theme.WindowsConsole
Install-Module -AllowPrerelease -Force -Verbose -Name TreeSize
Install-Module -AllowPrerelease -Force -Verbose -Name WindowsConsoleFonts
Install-Module -AllowPrerelease -Force -Verbose -Name WTToolBox
Install-Module -AllowPrerelease -Force -Verbose -Name xRobocopy
Install-Module -AllowPrerelease -Force -Verbose -Name xWindowsUpdate