Install-Module -Name 7Zip4Powershell
Install-Module -Name AudioDeviceCmdlets
Install-Module -Name Carbon
Install-Module -Name ChocolateyGet
Install-Module -Name CmdMode
Install-Module -Name Cobalt
Install-Module -Name CodeConversion
Install-Module -Name Configuration
Install-Module -Name Convert
Install-Module -Name DSCR_FileAssoc
Install-Module -Name EditorServicesCommandSuite
Install-Module -Name EzTheme
Install-Module -Name Foil
Install-Module -Name FontUtilities
Install-Module -Name Get-ActiveSession
Install-Module -Name Get-ChildItemColor
Install-Module -Name Get-MediaInfo
Install-Module -Name Graphical
Install-Module -Name GuiCompletion
Install-Module -Name IconForGUI
Install-Module -Name Logging
Install-Module -Name Metadata
Install-Module -Name Microsoft.PowerShell.Archive
Install-Module -Name Microsoft.PowerShell.ConsoleGuiTools
Install-Module -Name Microsoft.PowerShell.Crescendo
Install-Module -Name Microsoft.PowerShell.WhatsNew
Install-Module -Name ModuleBuilder
Install-Module -Name MSTerminalSettings
Install-Module -Name oh-my-posh
Install-Module -Name Pansies
Install-Module -Name platyPS
Install-Module -Name Posh-SSH
Install-Module -Name posh-sshell
Install-Module -Name PoshColor
Install-Module -Name PoshHosts
Install-Module -Name PoShLog
Install-Module -Name PowerLine
Install-Module -Name PowerRemoteDesktop_Server
Install-Module -Name PowerRemoteDesktop_Viewer
Install-Module -Name PowerShellCookbook
Install-Module -Name PowerShellForGitHub
Install-Module -Name PowerShellGet
Install-Module -Name ps2exe
Install-Module -Name PsComplete
Install-Module -Name PSConsoleTheme
Install-Module -Name PSDesiredStateConfiguration
Install-Module -Name PSEverything
Install-Module -Name PSExpandLine
Install-Module -Name PSFzf
Install-Module -Name PSGalleryExplorer
Install-Module -Name PSOneTools
Install-Module -Name PSParallel
Install-Module -Name PSPGP
Install-Module -Name PSReadLine
Install-Module -Name PSScriptAnalyzer
Install-Module -Name PSScriptMenuGui
Install-Module -Name PSScriptTools
Install-Module -Name PSStringTemplate
Install-Module -Name PSWindowsTermina
Install-Module -Name PSWindowsUpdate
Install-Module -Name TerminalBlocks
Install-Module -Name Theme.PowerShell
Install-Module -Name Theme.PSReadLine
Install-Module -Name Theme.WindowsConsole
Install-Module -Name TreeSize
Install-Module -Name WindowsConsoleFonts
Install-Module -Name WTToolBox
Install-Module -Name xRobocopy
Install-Module -Name xWindowsUpdate