
scoop install nerd-fonts/3270-NF
scoop install nerd-fonts/3270-NF-Mono
scoop install main/7zip
scoop install main/ack
scoop install nirsoft/activexcompatibilitymanager
scoop install nirsoft/activexhelper
scoop install nirsoft/adapterwatch
scoop install main/adb
scoop install nirsoft/addrview
scoop install extras/advancedrenamer
scoop install nirsoft/advancedrun
scoop install nerd-fonts/Agave-NF
scoop install nerd-fonts/Agave-NF-Mono
scoop install fonts/agave-slashed
scoop install extras/alacritty
scoop install nirsoft/allthreadsview
scoop install nirsoft/alternatestreamview
scoop install nirsoft/altstreamdump
scoop install DEV-Tools/AMPFontViewer
scoop install nerd-fonts/andika-compact
scoop install nerd-fonts/AnonymousPro-NF
scoop install nerd-fonts/AnonymousPro-NF-Mono
scoop install nerd-fonts/Anuphan
scoop install nirsoft/appaudioconfig
scoop install extras/appbuster
scoop install nirsoft/appcompatibilityview
scoop install nirsoft/appcrashview
scoop install nirsoft/appnetworkcounter
scoop install nirsoft/appreadwritecounter
scoop install main/aria2
scoop install nerd-fonts/Arimo-NF
scoop install nerd-fonts/Arimo-NF-Mono
scoop install nerd-fonts/AurulentSansMono-NF
scoop install nerd-fonts/AurulentSansMono-NF-Mono
scoop install main/autossh
scoop install nerd-fonts/Bai-Jamjuree
scoop install extras/baretail
scoop install nerd-fonts/basic-comical-nc
scoop install main/bat
scoop install nirsoft/batteryinfoview
scoop install nerd-fonts/BigBlueTerminal-NF
scoop install nerd-fonts/BigBlueTerminal-NF-Mono
scoop install main/binutils
scoop install nerd-fonts/BitstreamVeraSansMono-NF
scoop install nerd-fonts/BitstreamVeraSansMono-NF-Mono
scoop install nirsoft/bluescreenview
scoop install nirsoft/bluetoothcl
scoop install nirsoft/bluetoothlogview
scoop install nirsoft/bluetoothview
scoop install main/bottom
scoop install fonts/bront-dvsm
scoop install fonts/bront-um
scoop install main/broot
scoop install nirsoft/browseraddonsview
scoop install nirsoft/browserdownloadsview
scoop install nirsoft/browsinghistoryview
scoop install nirsoft/bulkfilechanger
scoop install nirsoft/bulletspassview
scoop install main/cacert
scoop install extras/caesium-image-compressor
scoop install extras/carnac
scoop install fonts/cascadiacode
scoop install nerd-fonts/CascadiaCode-NF
scoop install nerd-fonts/CascadiaCode-NF-Mono
scoop install fonts/cascadiacode-pl
scoop install fonts/cascadiamono-pl
scoop install main/ccat
scoop install nerd-fonts/Chakra-Petch
scoop install nerd-fonts/Charm
scoop install nerd-fonts/Charmonman
scoop install nerd-fonts/ChenYuLuoYen-Thin
scoop install main/chezmoi
scoop install nirsoft/chromecookiesview
scoop install main/chromedriver
scoop install nirsoft/chromehistoryview
scoop install nirsoft/cleanafterme
scoop install nirsoft/clipboardic
scoop install main/cmake
scoop install nerd-fonts/CodeNewRoman-NF
scoop install nerd-fonts/CodeNewRoman-NF-Mono
scoop install fonts/comicmono
scoop install nirsoft/controlmymonitor
scoop install extras/copyq
scoop install main/coreutils
scoop install nirsoft/countrytraceroute
scoop install fonts/courierprime
scoop install fonts/courierprimecode
scoop install fonts/courierprimemsb
scoop install fonts/courierprimesans
scoop install nerd-fonts/Cousine-NF
scoop install nerd-fonts/Cousine-NF-Mono
scoop install nirsoft/credentialsfileview
scoop install nirsoft/credhistview
scoop install extras/crystaldiskinfo
scoop install nirsoft/csvfileview
scoop install main/csview
scoop install main/curl
scoop install nirsoft/currports
scoop install nirsoft/currprocess
scoop install nirsoft/customexplorertoolbar
scoop install nirsoft/customizeie
scoop install DEV-Tools/Czkawka
scoop install extras/Czkawka-gui
scoop install nerd-fonts/DaddyTimeMono-NF
scoop install nerd-fonts/DaddyTimeMono-NF-Mono
scoop install main/dark
scoop install nirsoft/dataprotectiondecryptor
scoop install nerd-fonts/DejaVuSansMono-NF
scoop install nerd-fonts/DejaVuSansMono-NF-Mono
scoop install nerd-fonts/Delugia-Mono-Nerd-Font
scoop install nerd-fonts/Delugia-Mono-Nerd-Font-Complete
scoop install nerd-fonts/Delugia-Nerd-Font
scoop install nerd-fonts/Delugia-Nerd-Font-Book
scoop install nerd-fonts/Delugia-Nerd-Font-Complete
scoop install nirsoft/deviceioview
scoop install nirsoft/devmanview
scoop install main/diffutils
scoop install nirsoft/diskcountersview
scoop install nirsoft/disksmartview
scoop install nirsoft/dllexportviewer
scoop install main/dmg2img
scoop install nirsoft/dnsdataview
scoop install nirsoft/dnslookupview
scoop install nirsoft/dnsquerysniffer
scoop install nirsoft/domainhostingview
scoop install main/dos2unix
scoop install nirsoft/dotnetresourcesextract
scoop install nirsoft/downtester
scoop install nirsoft/driveletterview
scoop install nirsoft/driverview
scoop install nerd-fonts/DroidSansMono-NF
scoop install nerd-fonts/DroidSansMono-NF-Mono
scoop install nirsoft/dumpedid
scoop install extras/dupeguru
scoop install extras/echoargs
scoop install nirsoft/edgecookiesview
scoop install fonts/edlo
scoop install nirsoft/encryptedregview
scoop install nirsoft/eventlogchannelsview
scoop install nirsoft/eventlogsourcesview
scoop install extras/everything
scoop install main/everything-cli
scoop install nirsoft/executedprogramslist
scoop install nirsoft/extpassword
scoop install nerd-fonts/Fahkwang
scoop install fonts/fairfax
scoop install fonts/fairfax-sm
scoop install fonts/fairfaxhd
scoop install fonts/fairfaxhd-hax
scoop install fonts/fairfaxhd-sm
scoop install fonts/fairfaxserif
scoop install fonts/fairfaxserif-sm
scoop install nerd-fonts/FantasqueSansMono-NF
scoop install nerd-fonts/FantasqueSansMono-NF-Mono
scoop install main/far
scoop install nirsoft/fastresolver
scoop install nirsoft/favoritesview
scoop install nirsoft/fbcacheview
scoop install extras/fclones
scoop install main/fd
scoop install main/ffmpeg
scoop install extras/ffmpeg-batch
scoop install nirsoft/fileaccesserrorview
scoop install nirsoft/fileactivitywatch
scoop install nirsoft/filetypesman
scoop install nerd-fonts/FiraCode
scoop install nerd-fonts/FiraCode-NF
scoop install nerd-fonts/FiraCode-NF-Mono
scoop install nerd-fonts/FiraCode-Script
scoop install nerd-fonts/FiraMono-NF
scoop install nerd-fonts/FiraMono-NF-Mono
scoop install nirsoft/firefoxdownloadsview
scoop install nirsoft/firmwaretablesview
scoop install nirsoft/flashcookiesview
scoop install DEV-Tools/fman-np
scoop install nirsoft/folderchangesview
scoop install nirsoft/foldersreport
scoop install nirsoft/foldertimeupdate
scoop install nerd-fonts/Font-Awesome
scoop install extras/fontforge
scoop install main/fontreg
scoop install extras/freecommander
scoop install nirsoft/freespacelogview
scoop install main/fselect
scoop install nirsoft/fulleventlogview
scoop install main/fx
scoop install main/fzf
scoop install nirsoft/gacview
scoop install main/gcc
scoop install nirsoft/gdiview
scoop install main/gdrive
scoop install main/gdu
scoop install nirsoft/getnir
scoop install main/git
scoop install main/glslang
scoop install nerd-fonts/Go-Mono-NF
scoop install nerd-fonts/Go-Mono-NF-Mono
scoop install nerd-fonts/Gohu-NF
scoop install nerd-fonts/Gohu-NF-Mono
scoop install main/grep
scoop install main/grex
scoop install nirsoft/guipropview
scoop install main/gzip
scoop install nerd-fonts/Hack-NF
scoop install nerd-fonts/Hack-NF-Mono
scoop install nerd-fonts/HakushuGyosyoOiwai
scoop install nerd-fonts/HakushuKaisyoOiwai
scoop install nirsoft/handlecountersview
scoop install nirsoft/hashmyfiles
scoop install nerd-fonts/Hasklig
scoop install nerd-fonts/Hasklig-NF
scoop install nerd-fonts/Hasklig-NF-Mono
scoop install nirsoft/heapmemview
scoop install nerd-fonts/HeavyData-NF
scoop install nerd-fonts/HeavyData-NF-Mono
scoop install nerd-fonts/Hermit-NF
scoop install nerd-fonts/Hermit-NF-Mono
scoop install DEV-Tools/hitomi-downloader
scoop install w-bucket/hors
scoop install nirsoft/hostednetworkstarter
scoop install extras/hostsman
scoop install nirsoft/hotkeyslist
scoop install nirsoft/htmlastext
scoop install nirsoft/htmldocedit
scoop install main/htmlq
scoop install nirsoft/httpnetworksniffer
scoop install main/hyperfine
scoop install nerd-fonts/iA-Writer-NF
scoop install nerd-fonts/iA-Writer-NF-Mono
scoop install nerd-fonts/IBMPlexMono
scoop install nerd-fonts/IBMPlexMono-NF
scoop install nerd-fonts/IBMPlexMono-NF-Mono
scoop install nerd-fonts/IBMPlexSans
scoop install nerd-fonts/IBMPlexSans-Arabic
scoop install nerd-fonts/IBMPlexSans-Condensed
scoop install nerd-fonts/IBMPlexSans-Devanagari
scoop install nerd-fonts/IBMPlexSans-Hebrew
scoop install nerd-fonts/IBMPlexSans-JP
scoop install nerd-fonts/IBMPlexSans-KR
scoop install nerd-fonts/IBMPlexSans-Thai
scoop install nerd-fonts/IBMPlexSans-Thai-Looped
scoop install nerd-fonts/IBMPlexSerif
scoop install nirsoft/iconsextract
scoop install nirsoft/iecacheview
scoop install nirsoft/iedesignmode
scoop install igrep/igrep
scoop install nirsoft/imagecacheviewer
scoop install main/imagemagick
scoop install nerd-fonts/Inconsolata-NF
scoop install nerd-fonts/Inconsolata-NF-Mono
scoop install nerd-fonts/InconsolataGo-NF
scoop install nerd-fonts/InconsolataGo-NF-Mono
scoop install nerd-fonts/InconsolataLGC-NF
scoop install nerd-fonts/InconsolataLGC-NF-Mono
scoop install nirsoft/injecteddll
scoop install main/innounp
scoop install nirsoft/insideclipboard
scoop install nirsoft/installedappview
scoop install nirsoft/installedcodec
scoop install nirsoft/installeddriverslist
scoop install nirsoft/installedpackagesview
scoop install nerd-fonts/Iosevka-NF
scoop install nerd-fonts/Iosevka-NF-Mono
scoop install nerd-fonts/IPAex-Gothic
scoop install nerd-fonts/IPAex-Mincho
scoop install main/iperf3
scoop install nirsoft/ipinfooffline
scoop install nirsoft/ipneighborsview
scoop install nirsoft/ipnetinfo
scoop install nirsoft/javascriptanimatorexpress
scoop install main/jdupes
scoop install nerd-fonts/JetBrains-Mono
scoop install nerd-fonts/JetBrainsMono-NF
scoop install nerd-fonts/JetBrainsMono-NF-Mono
scoop install nerd-fonts/jf-open-huninn
scoop install main/jo
scoop install extras/joe
scoop install main/jq
scoop install nirsoft/jrview
scoop install fonts/juliamono
scoop install fonts/juliamono-latin
scoop install nirsoft/jumplistsview
scoop install nerd-fonts/K2D
scoop install nerd-fonts/Kanit
scoop install nirsoft/keyboardstateview
scoop install nerd-fonts/Kodchasan
scoop install nerd-fonts/KoHo
scoop install nerd-fonts/Krub
scoop install nirsoft/lastactivityview
scoop install nerd-fonts/Lato
scoop install nerd-fonts/LeagueMono-static
scoop install nerd-fonts/LeagueMono-variable
scoop install nerd-fonts/Lekton-NF
scoop install nerd-fonts/Lekton-NF-Mono
scoop install DEV-Tools/less
scoop install main/lftp
scoop install fonts/liberation
scoop install nerd-fonts/LiberationMono-NF
scoop install nerd-fonts/LiberationMono-NF-Mono
scoop install main/libxml2
scoop install fonts/lilex
scoop install fonts/lilex-variable
scoop install main/links
scoop install nirsoft/livetcpudpwatch
scoop install nirsoft/loadeddllsview
scoop install DEV-Tools/lockhunter
scoop install nirsoft/lsasecretsdump
scoop install nirsoft/lsasecretsview
scoop install main/lsd
scoop install main/lux
scoop install nerd-fonts/LXGW-Bright
scoop install nerd-fonts/LXGWWenKai
scoop install nerd-fonts/LXGWWenKaiMono
scoop install nerd-fonts/LXGWWenKaiScreen
scoop install nerd-fonts/LXGWWenKaiScreenR
scoop install nirsoft/macaddressview
scoop install nirsoft/madpassext
scoop install nirsoft/mailpassview
scoop install main/make
scoop install nerd-fonts/Mali
scoop install nirsoft/managewirelessnetworks
scoop install fonts/martianmono
scoop install fonts/martianmono-variable
scoop install extras/mc
scoop install main/mediainfo
scoop install nerd-fonts/Meslo-NF
scoop install nerd-fonts/Meslo-NF-Mono
scoop install nirsoft/messenpass
scoop install nirsoft/metarweather
scoop install main/micro
scoop install nerd-fonts/Mitr
scoop install DEV-Tools/mkcert
scoop install nirsoft/mmcompview
scoop install nirsoft/mmcsnapinsview
scoop install nirsoft/mobilefilesearch
scoop install nirsoft/monitorinfoview
scoop install nerd-fonts/Monofur-NF
scoop install nerd-fonts/Monofur-NF-Mono
scoop install nerd-fonts/Monoid-NF
scoop install nerd-fonts/Monoid-NF-Mono
scoop install nerd-fonts/Mononoki-NF
scoop install nerd-fonts/Mononoki-NF-Mono
scoop install fonts/montserrat
scoop install fonts/montserrat-alternates
scoop install main/mosh-client
scoop install nerd-fonts/MPlus-NF
scoop install nerd-fonts/MPlus-NF-Mono
scoop install nirsoft/muicacheview
scoop install extras/multicommander
scoop install nirsoft/multimonitortool
scoop install nirsoft/myeventviewer
scoop install nirsoft/mylastsearch
scoop install nirsoft/myuninstaller
scoop install nirsoft/mzcacheview
scoop install nirsoft/mzcookiesview
scoop install nirsoft/mzhistoryview
scoop install main/naiveproxy
scoop install main/nano
scoop install main/navi
scoop install extras/neatdownloadmanager
scoop install main/neofetch
scoop install main/neovim
scoop install nirsoft/netbscanner
scoop install main/netcat
scoop install nirsoft/netconnectchoose
scoop install nirsoft/netresview
scoop install nirsoft/netrouteview
scoop install nirsoft/networkconnectlog
scoop install nirsoft/networkcounterswatch
scoop install nirsoft/networkinterfacesview
scoop install nirsoft/networklatencyview
scoop install nirsoft/networkopenedfiles
scoop install nirsoft/networktrafficview
scoop install extras/nexusfont
scoop install main/ngrok
scoop install nerd-fonts/Niramit
scoop install main/nircmd
scoop install nirsoft/nirext
scoop install extras/nirlauncher
scoop install nirsoft/nk2edit
scoop install nirsoft/nk2view
scoop install main/nmap
scoop install main/nodejs
scoop install nirsoft/none
scoop install extras/notepadplusplus
scoop install nerd-fonts/Noto-CJK-Mega-OTC
scoop install nerd-fonts/Noto-NF
scoop install nerd-fonts/Noto-NF-Mono
scoop install nirsoft/ntfslinksview
scoop install main/nuget
scoop install nerd-fonts/Office-Code-Pro
scoop install fonts/officecodepro
scoop install fonts/officecodepro-d
scoop install nirsoft/officeins
scoop install nirsoft/offlineregistryfinder
scoop install nirsoft/offlineregistryview
scoop install java/ojdkbuild-jre
scoop install nerd-fonts/Open-Sans
scoop install nerd-fonts/OpenDyslexic-NF
scoop install nerd-fonts/OpenDyslexic-NF-Mono
scoop install nirsoft/openedfilesview
scoop install java/openjdk
scoop install nirsoft/opensavefilesview
scoop install main/openssh
scoop install main/openssl
scoop install extras/openvpn-connect
scoop install nirsoft/openwithview
scoop install nirsoft/operacacheview
scoop install nirsoft/operapassview
scoop install java/oraclejre8
scoop install nirsoft/outlookaccountsview
scoop install nirsoft/outlookaddressbookview
scoop install nirsoft/outlookattachview
scoop install nirsoft/outlookstatview
scoop install nerd-fonts/Overpass-NF
scoop install nerd-fonts/Overpass-NF-Mono
scoop install fonts/oxygenmono
scoop install extras/paint.net
scoop install nirsoft/passwordsecurityscanner
scoop install main/pastel
scoop install nerd-fonts/Pattaya
scoop install main/pdftk
scoop install extras/peazip
scoop install main/perl
scoop install main/pget
scoop install nirsoft/pinginfoview
scoop install main/poetry
scoop install nirsoft/previousfilesrecovery
scoop install nirsoft/processactivityview
scoop install nirsoft/processtcpsummary
scoop install nirsoft/processthreadsview
scoop install main/procs
scoop install nirsoft/productkeyscanner
scoop install nirsoft/produkey
scoop install nerd-fonts/ProFont-NF
scoop install nerd-fonts/ProFont-NF-Mono
scoop install nerd-fonts/ProggyClean-NF
scoop install nerd-fonts/ProggyClean-NF-Mono
scoop install nerd-fonts/Prompt
scoop install nirsoft/protectedstoragepassview
scoop install nirsoft/pstpassword
scoop install main/psutils
scoop install fonts/ptmono
scoop install fonts/ptsans
scoop install fonts/ptsans-expert
scoop install fonts/ptserif
scoop install fonts/ptserif-expert
scoop install main/python
scoop install extras/Q-dir
scoop install main/qr
scoop install DEV-Tools/quick-access-popup
scoop install nirsoft/quicksetdns
scoop install nerd-fonts/Raleway
scoop install main/rclone
scoop install extras/rclone-browser
scoop install nirsoft/recentfilesview
scoop install fonts/recmono-all
scoop install fonts/recmono-casual
scoop install fonts/recmono-duotone
scoop install fonts/recmono-linear
scoop install fonts/recmono-semicasual
scoop install fonts/recursive-all
scoop install nirsoft/regdllview
scoop install nirsoft/regfileexport
scoop install nirsoft/regfromapp
scoop install nirsoft/registrychangesview
scoop install nirsoft/regscanner
scoop install nirsoft/remotedesktoppassview
scoop install extras/renderdoc
scoop install nirsoft/resourcesextract
scoop install main/ripgrep
scoop install nerd-fonts/RobotoMono-NF
scoop install nerd-fonts/RobotoMono-NF-Mono
scoop install fonts/robotomono-variable
scoop install nerd-fonts/Rounded-L-Mplus
scoop install nerd-fonts/Rounded-Mplus
scoop install nerd-fonts/Rounded-X-Mplus
scoop install nirsoft/routerpassview
scoop install nirsoft/rtmpdumphelper
scoop install main/ruby
scoop install nirsoft/runasdate
scoop install extras/runcat
scoop install nirsoft/runfromprocess
scoop install main/rust
scoop install main/rustup-msvc
scoop install main/s
scoop install nirsoft/safaricacheview
scoop install nirsoft/safarihistoryview
scoop install nerd-fonts/Sarabun
scoop install extras/scoop-completion
scoop install DEV-Tools/scoop-search
scoop install main/sd
scoop install nirsoft/searchfilterview
scoop install nirsoft/securityquestionsview
scoop install nirsoft/securitysoftview
scoop install main/sed
scoop install main/selenium
scoop install nirsoft/seqdownload
scoop install nirsoft/serviwin
scoop install nerd-fonts/Setofont
scoop install extras/shadered
scoop install nirsoft/shadowcopyview
scoop install nerd-fonts/ShareTechMono-NF
scoop install nerd-fonts/ShareTechMono-NF-Mono
scoop install main/shasum
scoop install nirsoft/shellbagsview
scoop install nirsoft/shellexview
scoop install nirsoft/shellmenunew
scoop install nirsoft/shellmenuview
scoop install nirsoft/shortcutsman
scoop install nirsoft/simplecodegenerator
scoop install nirsoft/simpleprogramdebugger
scoop install nirsoft/simplewmiview
scoop install nirsoft/siteshoter
scoop install nirsoft/skypecontactsview
scoop install nirsoft/skypelogview
scoop install nirsoft/smartsniff
scoop install nirsoft/sniffpass
scoop install extras/so
scoop install nirsoft/socketsniff
scoop install fonts/sometypemono
scoop install nerd-fonts/Soukou-Mincho
scoop install nirsoft/soundvolumecommandline
scoop install nirsoft/soundvolumeview
scoop install nerd-fonts/Source-Han-Mega-OTC
scoop install nerd-fonts/Source-Han-Mono-HC
scoop install nerd-fonts/Source-Han-Mono-J
scoop install nerd-fonts/Source-Han-Mono-K
scoop install nerd-fonts/Source-Han-Mono-SC
scoop install nerd-fonts/Source-Han-Mono-TC
scoop install nerd-fonts/Source-Han-Noto-CJK-Ultra-OTC
scoop install nerd-fonts/Source-Han-Sans-HC
scoop install nerd-fonts/Source-Han-Sans-J
scoop install nerd-fonts/Source-Han-Sans-K
scoop install nerd-fonts/Source-Han-Sans-SC
scoop install nerd-fonts/Source-Han-Sans-TC
scoop install nerd-fonts/Source-Han-Serif-HC
scoop install nerd-fonts/Source-Han-Serif-J
scoop install nerd-fonts/Source-Han-Serif-K
scoop install nerd-fonts/Source-Han-Serif-SC
scoop install nerd-fonts/Source-Han-Serif-TC
scoop install fonts/sourcecodepro
scoop install nerd-fonts/SourceCodePro-NF
scoop install nerd-fonts/SourceCodePro-NF-Mono
scoop install fonts/sourcecodepro-variable
scoop install fonts/spacegrotesk
scoop install fonts/spacegrotesk-variable
scoop install nerd-fonts/SpaceMono-NF
scoop install nerd-fonts/SpaceMono-NF-Mono
scoop install nirsoft/specialfoldersview
scoop install main/speedtest-cli
scoop install main/sqlite
scoop install nerd-fonts/Sriracha
scoop install nerd-fonts/Srisakdi
scoop install nirsoft/startuprun
scoop install main/sudo
scoop install main/syncthing
scoop install nirsoft/sysexporter
scoop install nirsoft/tabletextcompare
scoop install nerd-fonts/taipei-sans
scoop install nerd-fonts/Tanuki-Permanent-Marker
scoop install main/tar
scoop install nirsoft/taskschedulerview
scoop install nirsoft/tcpconnectproblemview
scoop install nirsoft/tcplogview
scoop install nonportable/teracopy-np
scoop install extras/terminal-icons
scoop install nerd-fonts/Terminus-NF
scoop install nerd-fonts/Terminus-NF-Mono
scoop install DEV-Tools/thisiswin11
scoop install nirsoft/timezonesview
scoop install fonts/tinos
scoop install nerd-fonts/Tinos-NF
scoop install nerd-fonts/Tinos-NF-Mono
scoop install nerd-fonts/Tiresias
scoop install main/tldr
scoop install extras/totalcommander
scoop install DEV-Tools/touch
scoop install main/tre-command
scoop install main/trid
scoop install nirsoft/turnedontimesview
scoop install nerd-fonts/Ubuntu-NF
scoop install nerd-fonts/Ubuntu-NF-Mono
scoop install nerd-fonts/UbuntuMono-NF
scoop install nerd-fonts/UbuntuMono-NF-Mono
scoop install nirsoft/uninstallview
scoop install main/unrar
scoop install main/unzip
scoop install nirsoft/urlprotocolview
scoop install nirsoft/urlstringgrabber
scoop install nirsoft/usbdeview
scoop install nirsoft/usbdrivelog
scoop install nirsoft/usblogview
scoop install nirsoft/userassistview
scoop install nirsoft/userprofilesview
scoop install extras/util-linux-ng
scoop install nirsoft/vaultpasswordview
scoop install main/vcpkg
scoop install extras/vcredist2022
scoop install nerd-fonts/Victor-Mono
scoop install nerd-fonts/VictorMono-NF
scoop install nerd-fonts/VictorMono-NF-Mono
scoop install nirsoft/videocacheview
scoop install main/vim
scoop install main/vmaf
scoop install nirsoft/vncpassview
scoop install extras/vncviewer
scoop install nirsoft/volumouse
scoop install main/vt-cli
scoop install nirsoft/wakemeonlan
scoop install main/watchexec
scoop install nirsoft/webbrowserbookmarksview
scoop install nirsoft/webcacheimageinfo
scoop install nirsoft/webcamimagesave
scoop install nirsoft/webcookiessniffer
scoop install nirsoft/websitesniffer
scoop install nirsoft/webvideocap
scoop install nerd-fonts/Wenquanyi-Microhei
scoop install nerd-fonts/Wenquanyi-Zenhei
scoop install DEV-Tools/wget
scoop install nirsoft/whatinstartup
scoop install nirsoft/whatishang
scoop install main/which
scoop install nirsoft/whoiscl
scoop install nirsoft/whoisconnectedsniffer
scoop install fonts/whoismono
scoop install nirsoft/whoisthisdomain
scoop install nirsoft/whosip
scoop install nirsoft/wifichannelmonitor
scoop install nirsoft/wifidiagnosticsview
scoop install nirsoft/wifihistoryview
scoop install extras/winauth
scoop install nirsoft/wincrashreport
scoop install nirsoft/windeflogview
scoop install nirsoft/windefthreatsview
scoop install extras/windiff
scoop install nirsoft/windowspasswordrecoverypackage
scoop install nirsoft/windowsupdateshistoryviewer
scoop install nirsoft/winexplorer
scoop install main/winfetch
scoop install nirsoft/winfontsview
scoop install extras/wingetui
scoop install nirsoft/winlister
scoop install nirsoft/winlogonview
scoop install nirsoft/winmailpassrec
scoop install extras/winmerge
scoop install nirsoft/winprefetchview
scoop install extras/winscp
scoop install nirsoft/winsockservicesview
scoop install nirsoft/winupdateslist
scoop install nirsoft/wirelessconnectioninfo
scoop install nirsoft/wirelesskeydump
scoop install nirsoft/wirelesskeyview
scoop install nirsoft/wirelessnetconsole
scoop install nirsoft/wirelessnetview
scoop install nirsoft/wirelessnetworkwatcher
scoop install fonts/worksans
scoop install fonts/worksans-variable
scoop install fonts/writer
scoop install extras/wsa-pacman
scoop install main/wttop
scoop install fonts/xkcd-script
scoop install extras/ydl-ui
scoop install main/youtube-dl
scoop install extras/ytdlp-interface
scoop install main/zip
scoop install nirsoft/zipinstaller
scoop install main/zoxide
scoop install nerd-fonts/3270-NF
scoop install nerd-fonts/3270-NF-Mono
scoop install main/7zip
scoop install main/ack
scoop install nirsoft/activexcompatibilitymanager
scoop install nirsoft/activexhelper
scoop install nirsoft/adapterwatch
scoop install main/adb
scoop install nirsoft/addrview
scoop install extras/advancedrenamer
scoop install nirsoft/advancedrun
scoop install nerd-fonts/Agave-NF
scoop install nerd-fonts/Agave-NF-Mono
scoop install fonts/agave-slashed
scoop install extras/alacritty
scoop install nirsoft/allthreadsview
scoop install nirsoft/alternatestreamview
scoop install nirsoft/altstreamdump
scoop install DEV-Tools/AMPFontViewer
scoop install nerd-fonts/andika-compact
scoop install nerd-fonts/AnonymousPro-NF
scoop install nerd-fonts/AnonymousPro-NF-Mono
scoop install nerd-fonts/Anuphan
scoop install nirsoft/appaudioconfig
scoop install extras/appbuster
scoop install nirsoft/appcompatibilityview
scoop install nirsoft/appcrashview
scoop install nirsoft/appnetworkcounter
scoop install nirsoft/appreadwritecounter
scoop install main/aria2
scoop install nerd-fonts/Arimo-NF
scoop install nerd-fonts/Arimo-NF-Mono
scoop install nerd-fonts/AurulentSansMono-NF
scoop install nerd-fonts/AurulentSansMono-NF-Mono
scoop install main/autossh
scoop install nerd-fonts/Bai-Jamjuree
scoop install extras/baretail
scoop install nerd-fonts/basic-comical-nc
scoop install main/bat
scoop install nirsoft/batteryinfoview
scoop install nerd-fonts/BigBlueTerminal-NF
scoop install nerd-fonts/BigBlueTerminal-NF-Mono
scoop install main/binutils
scoop install nerd-fonts/BitstreamVeraSansMono-NF
scoop install nerd-fonts/BitstreamVeraSansMono-NF-Mono
scoop install nirsoft/bluescreenview
scoop install nirsoft/bluetoothcl
scoop install nirsoft/bluetoothlogview
scoop install nirsoft/bluetoothview
scoop install main/bottom
scoop install fonts/bront-dvsm
scoop install fonts/bront-um
scoop install main/broot
scoop install nirsoft/browseraddonsview
scoop install nirsoft/browserdownloadsview
scoop install nirsoft/browsinghistoryview
scoop install nirsoft/bulkfilechanger
scoop install nirsoft/bulletspassview
scoop install main/cacert
scoop install extras/caesium-image-compressor
scoop install extras/carnac
scoop install fonts/cascadiacode
scoop install nerd-fonts/CascadiaCode-NF
scoop install nerd-fonts/CascadiaCode-NF-Mono
scoop install fonts/cascadiacode-pl
scoop install fonts/cascadiamono-pl
scoop install main/ccat
scoop install nerd-fonts/Chakra-Petch
scoop install nerd-fonts/Charm
scoop install nerd-fonts/Charmonman
scoop install nerd-fonts/ChenYuLuoYen-Thin
scoop install main/chezmoi
scoop install nirsoft/chromecookiesview
scoop install main/chromedriver
scoop install nirsoft/chromehistoryview
scoop install nirsoft/cleanafterme
scoop install nirsoft/clipboardic
scoop install main/cmake
scoop install nerd-fonts/CodeNewRoman-NF
scoop install nerd-fonts/CodeNewRoman-NF-Mono
scoop install fonts/comicmono
scoop install nirsoft/controlmymonitor
scoop install extras/copyq
scoop install main/coreutils
scoop install nirsoft/countrytraceroute
scoop install fonts/courierprime
scoop install fonts/courierprimecode
scoop install fonts/courierprimemsb
scoop install fonts/courierprimesans
scoop install nerd-fonts/Cousine-NF
scoop install nerd-fonts/Cousine-NF-Mono
scoop install nirsoft/credentialsfileview
scoop install nirsoft/credhistview
scoop install extras/crystaldiskinfo
scoop install nirsoft/csvfileview
scoop install main/csview
scoop install main/curl
scoop install nirsoft/currports
scoop install nirsoft/currprocess
scoop install nirsoft/customexplorertoolbar
scoop install nirsoft/customizeie
scoop install DEV-Tools/Czkawka
scoop install extras/Czkawka-gui
scoop install nerd-fonts/DaddyTimeMono-NF
scoop install nerd-fonts/DaddyTimeMono-NF-Mono
scoop install main/dark
scoop install nirsoft/dataprotectiondecryptor
scoop install nerd-fonts/DejaVuSansMono-NF
scoop install nerd-fonts/DejaVuSansMono-NF-Mono
scoop install nerd-fonts/Delugia-Mono-Nerd-Font
scoop install nerd-fonts/Delugia-Mono-Nerd-Font-Complete
scoop install nerd-fonts/Delugia-Nerd-Font
scoop install nerd-fonts/Delugia-Nerd-Font-Book
scoop install nerd-fonts/Delugia-Nerd-Font-Complete
scoop install nirsoft/deviceioview
scoop install nirsoft/devmanview
scoop install main/diffutils
scoop install nirsoft/diskcountersview
scoop install nirsoft/disksmartview
scoop install nirsoft/dllexportviewer
scoop install main/dmg2img
scoop install nirsoft/dnsdataview
scoop install nirsoft/dnslookupview
scoop install nirsoft/dnsquerysniffer
scoop install nirsoft/domainhostingview
scoop install main/dos2unix
scoop install nirsoft/dotnetresourcesextract
scoop install nirsoft/downtester
scoop install nirsoft/driveletterview
scoop install nirsoft/driverview
scoop install nerd-fonts/DroidSansMono-NF
scoop install nerd-fonts/DroidSansMono-NF-Mono
scoop install nirsoft/dumpedid
scoop install extras/dupeguru
scoop install extras/echoargs
scoop install nirsoft/edgecookiesview
scoop install fonts/edlo
scoop install nirsoft/encryptedregview
scoop install nirsoft/eventlogchannelsview
scoop install nirsoft/eventlogsourcesview
scoop install extras/everything
scoop install main/everything-cli
scoop install nirsoft/executedprogramslist
scoop install nirsoft/extpassword
scoop install nerd-fonts/Fahkwang
scoop install fonts/fairfax
scoop install fonts/fairfax-sm
scoop install fonts/fairfaxhd
scoop install fonts/fairfaxhd-hax
scoop install fonts/fairfaxhd-sm
scoop install fonts/fairfaxserif
scoop install fonts/fairfaxserif-sm
scoop install nerd-fonts/FantasqueSansMono-NF
scoop install nerd-fonts/FantasqueSansMono-NF-Mono
scoop install main/far
scoop install nirsoft/fastresolver
scoop install nirsoft/favoritesview
scoop install nirsoft/fbcacheview
scoop install extras/fclones
scoop install main/fd
scoop install main/ffmpeg
scoop install extras/ffmpeg-batch
scoop install nirsoft/fileaccesserrorview
scoop install nirsoft/fileactivitywatch
scoop install nirsoft/filetypesman
scoop install nerd-fonts/FiraCode
scoop install nerd-fonts/FiraCode-NF
scoop install nerd-fonts/FiraCode-NF-Mono
scoop install nerd-fonts/FiraCode-Script
scoop install nerd-fonts/FiraMono-NF
scoop install nerd-fonts/FiraMono-NF-Mono
scoop install nirsoft/firefoxdownloadsview
scoop install nirsoft/firmwaretablesview
scoop install nirsoft/flashcookiesview
scoop install DEV-Tools/fman-np
scoop install nirsoft/folderchangesview
scoop install nirsoft/foldersreport
scoop install nirsoft/foldertimeupdate
scoop install nerd-fonts/Font-Awesome
scoop install extras/fontforge
scoop install main/fontreg
scoop install extras/freecommander
scoop install nirsoft/freespacelogview
scoop install main/fselect
scoop install nirsoft/fulleventlogview
scoop install main/fx
scoop install main/fzf
scoop install nirsoft/gacview
scoop install main/gcc
scoop install nirsoft/gdiview
scoop install main/gdrive
scoop install main/gdu
scoop install nirsoft/getnir
scoop install main/git
scoop install main/glslang
scoop install nerd-fonts/Go-Mono-NF
scoop install nerd-fonts/Go-Mono-NF-Mono
scoop install nerd-fonts/Gohu-NF
scoop install nerd-fonts/Gohu-NF-Mono
scoop install main/grep
scoop install main/grex
scoop install nirsoft/guipropview
scoop install main/gzip
scoop install nerd-fonts/Hack-NF
scoop install nerd-fonts/Hack-NF-Mono
scoop install nerd-fonts/HakushuGyosyoOiwai
scoop install nerd-fonts/HakushuKaisyoOiwai
scoop install nirsoft/handlecountersview
scoop install nirsoft/hashmyfiles
scoop install nerd-fonts/Hasklig
scoop install nerd-fonts/Hasklig-NF
scoop install nerd-fonts/Hasklig-NF-Mono
scoop install nirsoft/heapmemview
scoop install nerd-fonts/HeavyData-NF
scoop install nerd-fonts/HeavyData-NF-Mono
scoop install nerd-fonts/Hermit-NF
scoop install nerd-fonts/Hermit-NF-Mono
scoop install DEV-Tools/hitomi-downloader
scoop install w-bucket/hors
scoop install nirsoft/hostednetworkstarter
scoop install extras/hostsman
scoop install nirsoft/hotkeyslist
scoop install nirsoft/htmlastext
scoop install nirsoft/htmldocedit
scoop install main/htmlq
scoop install nirsoft/httpnetworksniffer
scoop install main/hyperfine
scoop install nerd-fonts/iA-Writer-NF
scoop install nerd-fonts/iA-Writer-NF-Mono
scoop install nerd-fonts/IBMPlexMono
scoop install nerd-fonts/IBMPlexMono-NF
scoop install nerd-fonts/IBMPlexMono-NF-Mono
scoop install nerd-fonts/IBMPlexSans
scoop install nerd-fonts/IBMPlexSans-Arabic
scoop install nerd-fonts/IBMPlexSans-Condensed
scoop install nerd-fonts/IBMPlexSans-Devanagari
scoop install nerd-fonts/IBMPlexSans-Hebrew
scoop install nerd-fonts/IBMPlexSans-JP
scoop install nerd-fonts/IBMPlexSans-KR
scoop install nerd-fonts/IBMPlexSans-Thai
scoop install nerd-fonts/IBMPlexSans-Thai-Looped
scoop install nerd-fonts/IBMPlexSerif
scoop install nirsoft/iconsextract
scoop install nirsoft/iecacheview
scoop install nirsoft/iedesignmode
scoop install igrep/igrep
scoop install nirsoft/imagecacheviewer
scoop install main/imagemagick
scoop install nerd-fonts/Inconsolata-NF
scoop install nerd-fonts/Inconsolata-NF-Mono
scoop install nerd-fonts/InconsolataGo-NF
scoop install nerd-fonts/InconsolataGo-NF-Mono
scoop install nerd-fonts/InconsolataLGC-NF
scoop install nerd-fonts/InconsolataLGC-NF-Mono
scoop install nirsoft/injecteddll
scoop install main/innounp
scoop install nirsoft/insideclipboard
scoop install nirsoft/installedappview
scoop install nirsoft/installedcodec
scoop install nirsoft/installeddriverslist
scoop install nirsoft/installedpackagesview
scoop install nerd-fonts/Iosevka-NF
scoop install nerd-fonts/Iosevka-NF-Mono
scoop install nerd-fonts/IPAex-Gothic
scoop install nerd-fonts/IPAex-Mincho
scoop install main/iperf3
scoop install nirsoft/ipinfooffline
scoop install nirsoft/ipneighborsview
scoop install nirsoft/ipnetinfo
scoop install nirsoft/javascriptanimatorexpress
scoop install main/jdupes
scoop install nerd-fonts/JetBrains-Mono
scoop install nerd-fonts/JetBrainsMono-NF
scoop install nerd-fonts/JetBrainsMono-NF-Mono
scoop install nerd-fonts/jf-open-huninn
scoop install main/jo
scoop install extras/joe
scoop install main/jq
scoop install nirsoft/jrview
scoop install fonts/juliamono
scoop install fonts/juliamono-latin
scoop install nirsoft/jumplistsview
scoop install nerd-fonts/K2D
scoop install nerd-fonts/Kanit
scoop install nirsoft/keyboardstateview
scoop install nerd-fonts/Kodchasan
scoop install nerd-fonts/KoHo
scoop install nerd-fonts/Krub
scoop install nirsoft/lastactivityview
scoop install nerd-fonts/Lato
scoop install nerd-fonts/LeagueMono-static
scoop install nerd-fonts/LeagueMono-variable
scoop install nerd-fonts/Lekton-NF
scoop install nerd-fonts/Lekton-NF-Mono
scoop install DEV-Tools/less
scoop install main/lftp
scoop install fonts/liberation
scoop install nerd-fonts/LiberationMono-NF
scoop install nerd-fonts/LiberationMono-NF-Mono
scoop install main/libxml2
scoop install fonts/lilex
scoop install fonts/lilex-variable
scoop install main/links
scoop install nirsoft/livetcpudpwatch
scoop install nirsoft/loadeddllsview
scoop install DEV-Tools/lockhunter
scoop install nirsoft/lsasecretsdump
scoop install nirsoft/lsasecretsview
scoop install main/lsd
scoop install main/lux
scoop install nerd-fonts/LXGW-Bright
scoop install nerd-fonts/LXGWWenKai
scoop install nerd-fonts/LXGWWenKaiMono
scoop install nerd-fonts/LXGWWenKaiScreen
scoop install nerd-fonts/LXGWWenKaiScreenR
scoop install nirsoft/macaddressview
scoop install nirsoft/madpassext
scoop install nirsoft/mailpassview
scoop install main/make
scoop install nerd-fonts/Mali
scoop install nirsoft/managewirelessnetworks
scoop install fonts/martianmono
scoop install fonts/martianmono-variable
scoop install extras/mc
scoop install main/mediainfo
scoop install nerd-fonts/Meslo-NF
scoop install nerd-fonts/Meslo-NF-Mono
scoop install nirsoft/messenpass
scoop install nirsoft/metarweather
scoop install main/micro
scoop install nerd-fonts/Mitr
scoop install DEV-Tools/mkcert
scoop install nirsoft/mmcompview
scoop install nirsoft/mmcsnapinsview
scoop install nirsoft/mobilefilesearch
scoop install nirsoft/monitorinfoview
scoop install nerd-fonts/Monofur-NF
scoop install nerd-fonts/Monofur-NF-Mono
scoop install nerd-fonts/Monoid-NF
scoop install nerd-fonts/Monoid-NF-Mono
scoop install nerd-fonts/Mononoki-NF
scoop install nerd-fonts/Mononoki-NF-Mono
scoop install fonts/montserrat
scoop install fonts/montserrat-alternates
scoop install main/mosh-client
scoop install nerd-fonts/MPlus-NF
scoop install nerd-fonts/MPlus-NF-Mono
scoop install nirsoft/muicacheview
scoop install extras/multicommander
scoop install nirsoft/multimonitortool
scoop install nirsoft/myeventviewer
scoop install nirsoft/mylastsearch
scoop install nirsoft/myuninstaller
scoop install nirsoft/mzcacheview
scoop install nirsoft/mzcookiesview
scoop install nirsoft/mzhistoryview
scoop install main/naiveproxy
scoop install main/nano
scoop install main/navi
scoop install extras/neatdownloadmanager
scoop install main/neofetch
scoop install main/neovim
scoop install nirsoft/netbscanner
scoop install main/netcat
scoop install nirsoft/netconnectchoose
scoop install nirsoft/netresview
scoop install nirsoft/netrouteview
scoop install nirsoft/networkconnectlog
scoop install nirsoft/networkcounterswatch
scoop install nirsoft/networkinterfacesview
scoop install nirsoft/networklatencyview
scoop install nirsoft/networkopenedfiles
scoop install nirsoft/networktrafficview
scoop install extras/nexusfont
scoop install main/ngrok
scoop install nerd-fonts/Niramit
scoop install main/nircmd
scoop install nirsoft/nirext
scoop install extras/nirlauncher
scoop install nirsoft/nk2edit
scoop install nirsoft/nk2view
scoop install main/nmap
scoop install main/nodejs
scoop install nirsoft/none
scoop install extras/notepadplusplus
scoop install nerd-fonts/Noto-CJK-Mega-OTC
scoop install nerd-fonts/Noto-NF
scoop install nerd-fonts/Noto-NF-Mono
scoop install nirsoft/ntfslinksview
scoop install main/nuget
scoop install nerd-fonts/Office-Code-Pro
scoop install fonts/officecodepro
scoop install fonts/officecodepro-d
scoop install nirsoft/officeins
scoop install nirsoft/offlineregistryfinder
scoop install nirsoft/offlineregistryview
scoop install java/ojdkbuild-jre
scoop install nerd-fonts/Open-Sans
scoop install nerd-fonts/OpenDyslexic-NF
scoop install nerd-fonts/OpenDyslexic-NF-Mono
scoop install nirsoft/openedfilesview
scoop install java/openjdk
scoop install nirsoft/opensavefilesview
scoop install main/openssh
scoop install main/openssl
scoop install extras/openvpn-connect
scoop install nirsoft/openwithview
scoop install nirsoft/operacacheview
scoop install nirsoft/operapassview
scoop install java/oraclejre8
scoop install nirsoft/outlookaccountsview
scoop install nirsoft/outlookaddressbookview
scoop install nirsoft/outlookattachview
scoop install nirsoft/outlookstatview
scoop install nerd-fonts/Overpass-NF
scoop install nerd-fonts/Overpass-NF-Mono
scoop install fonts/oxygenmono
scoop install extras/paint.net
scoop install nirsoft/passwordsecurityscanner
scoop install main/pastel
scoop install nerd-fonts/Pattaya
scoop install main/pdftk
scoop install extras/peazip
scoop install main/perl
scoop install main/pget
scoop install nirsoft/pinginfoview
scoop install main/poetry
scoop install nirsoft/previousfilesrecovery
scoop install nirsoft/processactivityview
scoop install nirsoft/processtcpsummary
scoop install nirsoft/processthreadsview
scoop install main/procs
scoop install nirsoft/productkeyscanner
scoop install nirsoft/produkey
scoop install nerd-fonts/ProFont-NF
scoop install nerd-fonts/ProFont-NF-Mono
scoop install nerd-fonts/ProggyClean-NF
scoop install nerd-fonts/ProggyClean-NF-Mono
scoop install nerd-fonts/Prompt
scoop install nirsoft/protectedstoragepassview
scoop install nirsoft/pstpassword
scoop install main/psutils
scoop install fonts/ptmono
scoop install fonts/ptsans
scoop install fonts/ptsans-expert
scoop install fonts/ptserif
scoop install fonts/ptserif-expert
scoop install main/python
scoop install extras/Q-dir
scoop install main/qr
scoop install DEV-Tools/quick-access-popup
scoop install nirsoft/quicksetdns
scoop install nerd-fonts/Raleway
scoop install main/rclone
scoop install extras/rclone-browser
scoop install nirsoft/recentfilesview
scoop install fonts/recmono-all
scoop install fonts/recmono-casual
scoop install fonts/recmono-duotone
scoop install fonts/recmono-linear
scoop install fonts/recmono-semicasual
scoop install fonts/recursive-all
scoop install nirsoft/regdllview
scoop install nirsoft/regfileexport
scoop install nirsoft/regfromapp
scoop install nirsoft/registrychangesview
scoop install nirsoft/regscanner
scoop install nirsoft/remotedesktoppassview
scoop install extras/renderdoc
scoop install nirsoft/resourcesextract
scoop install main/ripgrep
scoop install nerd-fonts/RobotoMono-NF
scoop install nerd-fonts/RobotoMono-NF-Mono
scoop install fonts/robotomono-variable
scoop install nerd-fonts/Rounded-L-Mplus
scoop install nerd-fonts/Rounded-Mplus
scoop install nerd-fonts/Rounded-X-Mplus
scoop install nirsoft/routerpassview
scoop install nirsoft/rtmpdumphelper
scoop install main/ruby
scoop install nirsoft/runasdate
scoop install extras/runcat
scoop install nirsoft/runfromprocess
scoop install main/rust
scoop install main/rustup-msvc
scoop install main/s
scoop install nirsoft/safaricacheview
scoop install nirsoft/safarihistoryview
scoop install nerd-fonts/Sarabun
scoop install extras/scoop-completion
scoop install DEV-Tools/scoop-search
scoop install main/sd
scoop install nirsoft/searchfilterview
scoop install nirsoft/securityquestionsview
scoop install nirsoft/securitysoftview
scoop install main/sed
scoop install main/selenium
scoop install nirsoft/seqdownload
scoop install nirsoft/serviwin
scoop install nerd-fonts/Setofont
scoop install extras/shadered
scoop install nirsoft/shadowcopyview
scoop install nerd-fonts/ShareTechMono-NF
scoop install nerd-fonts/ShareTechMono-NF-Mono
scoop install main/shasum
scoop install nirsoft/shellbagsview
scoop install nirsoft/shellexview
scoop install nirsoft/shellmenunew
scoop install nirsoft/shellmenuview
scoop install nirsoft/shortcutsman
scoop install nirsoft/simplecodegenerator
scoop install nirsoft/simpleprogramdebugger
scoop install nirsoft/simplewmiview
scoop install nirsoft/siteshoter
scoop install nirsoft/skypecontactsview
scoop install nirsoft/skypelogview
scoop install nirsoft/smartsniff
scoop install nirsoft/sniffpass
scoop install extras/so
scoop install nirsoft/socketsniff
scoop install fonts/sometypemono
scoop install nerd-fonts/Soukou-Mincho
scoop install nirsoft/soundvolumecommandline
scoop install nirsoft/soundvolumeview
scoop install nerd-fonts/Source-Han-Mega-OTC
scoop install nerd-fonts/Source-Han-Mono-HC
scoop install nerd-fonts/Source-Han-Mono-J
scoop install nerd-fonts/Source-Han-Mono-K
scoop install nerd-fonts/Source-Han-Mono-SC
scoop install nerd-fonts/Source-Han-Mono-TC
scoop install nerd-fonts/Source-Han-Noto-CJK-Ultra-OTC
scoop install nerd-fonts/Source-Han-Sans-HC
scoop install nerd-fonts/Source-Han-Sans-J
scoop install nerd-fonts/Source-Han-Sans-K
scoop install nerd-fonts/Source-Han-Sans-SC
scoop install nerd-fonts/Source-Han-Sans-TC
scoop install nerd-fonts/Source-Han-Serif-HC
scoop install nerd-fonts/Source-Han-Serif-J
scoop install nerd-fonts/Source-Han-Serif-K
scoop install nerd-fonts/Source-Han-Serif-SC
scoop install nerd-fonts/Source-Han-Serif-TC
scoop install fonts/sourcecodepro
scoop install nerd-fonts/SourceCodePro-NF
scoop install nerd-fonts/SourceCodePro-NF-Mono
scoop install fonts/sourcecodepro-variable
scoop install fonts/spacegrotesk
scoop install fonts/spacegrotesk-variable
scoop install nerd-fonts/SpaceMono-NF
scoop install nerd-fonts/SpaceMono-NF-Mono
scoop install nirsoft/specialfoldersview
scoop install main/speedtest-cli
scoop install main/sqlite
scoop install nerd-fonts/Sriracha
scoop install nerd-fonts/Srisakdi
scoop install nirsoft/startuprun
scoop install main/sudo
scoop install main/syncthing
scoop install nirsoft/sysexporter
scoop install nirsoft/tabletextcompare
scoop install nerd-fonts/taipei-sans
scoop install nerd-fonts/Tanuki-Permanent-Marker
scoop install main/tar
scoop install nirsoft/taskschedulerview
scoop install nirsoft/tcpconnectproblemview
scoop install nirsoft/tcplogview
scoop install nonportable/teracopy-np
scoop install extras/terminal-icons
scoop install nerd-fonts/Terminus-NF
scoop install nerd-fonts/Terminus-NF-Mono
scoop install DEV-Tools/thisiswin11
scoop install nirsoft/timezonesview
scoop install fonts/tinos
scoop install nerd-fonts/Tinos-NF
scoop install nerd-fonts/Tinos-NF-Mono
scoop install nerd-fonts/Tiresias
scoop install main/tldr
scoop install extras/totalcommander
scoop install DEV-Tools/touch
scoop install main/tre-command
scoop install main/trid
scoop install nirsoft/turnedontimesview
scoop install nerd-fonts/Ubuntu-NF
scoop install nerd-fonts/Ubuntu-NF-Mono
scoop install nerd-fonts/UbuntuMono-NF
scoop install nerd-fonts/UbuntuMono-NF-Mono
scoop install nirsoft/uninstallview
scoop install main/unrar
scoop install main/unzip
scoop install nirsoft/urlprotocolview
scoop install nirsoft/urlstringgrabber
scoop install nirsoft/usbdeview
scoop install nirsoft/usbdrivelog
scoop install nirsoft/usblogview
scoop install nirsoft/userassistview
scoop install nirsoft/userprofilesview
scoop install extras/util-linux-ng
scoop install nirsoft/vaultpasswordview
scoop install main/vcpkg
scoop install extras/vcredist2022
scoop install nerd-fonts/Victor-Mono
scoop install nerd-fonts/VictorMono-NF
scoop install nerd-fonts/VictorMono-NF-Mono
scoop install nirsoft/videocacheview
scoop install main/vim
scoop install main/vmaf
scoop install nirsoft/vncpassview
scoop install extras/vncviewer
scoop install nirsoft/volumouse
scoop install main/vt-cli
scoop install nirsoft/wakemeonlan
scoop install main/watchexec
scoop install nirsoft/webbrowserbookmarksview
scoop install nirsoft/webcacheimageinfo
scoop install nirsoft/webcamimagesave
scoop install nirsoft/webcookiessniffer
scoop install nirsoft/websitesniffer
scoop install nirsoft/webvideocap
scoop install nerd-fonts/Wenquanyi-Microhei
scoop install nerd-fonts/Wenquanyi-Zenhei
scoop install DEV-Tools/wget
scoop install nirsoft/whatinstartup
scoop install nirsoft/whatishang
scoop install main/which
scoop install nirsoft/whoiscl
scoop install nirsoft/whoisconnectedsniffer
scoop install fonts/whoismono
scoop install nirsoft/whoisthisdomain
scoop install nirsoft/whosip
scoop install nirsoft/wifichannelmonitor
scoop install nirsoft/wifidiagnosticsview
scoop install nirsoft/wifihistoryview
scoop install extras/winauth
scoop install nirsoft/wincrashreport
scoop install nirsoft/windeflogview
scoop install nirsoft/windefthreatsview
scoop install extras/windiff
scoop install nirsoft/windowspasswordrecoverypackage
scoop install nirsoft/windowsupdateshistoryviewer
scoop install nirsoft/winexplorer
scoop install main/winfetch
scoop install nirsoft/winfontsview
scoop install extras/wingetui
scoop install nirsoft/winlister
scoop install nirsoft/winlogonview
scoop install nirsoft/winmailpassrec
scoop install extras/winmerge
scoop install nirsoft/winprefetchview
scoop install extras/winscp
scoop install nirsoft/winsockservicesview
scoop install nirsoft/winupdateslist
scoop install nirsoft/wirelessconnectioninfo
scoop install nirsoft/wirelesskeydump
scoop install nirsoft/wirelesskeyview
scoop install nirsoft/wirelessnetconsole
scoop install nirsoft/wirelessnetview
scoop install nirsoft/wirelessnetworkwatcher
scoop install fonts/worksans
scoop install fonts/worksans-variable
scoop install fonts/writer
scoop install extras/wsa-pacman
scoop install main/wttop
scoop install fonts/xkcd-script
scoop install extras/ydl-ui
scoop install main/youtube-dl
scoop install extras/ytdlp-interface
scoop install main/zip
scoop install nirsoft/zipinstaller
scoop install main/zoxide

